#!/usr/bin/env node
/**
 * GPL-3.0 — Channel extension build
 * Usage: node scripts/build-channel.mjs <channel-id>
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const channelId = process.argv[2];
if (!channelId) {
    console.error("Usage: npm run build -- <channel-id>");
    console.error("Example: npm run build -- xiaoetong");
    process.exit(1);
}

const channelDir = path.join(ROOT, "channels", channelId);
const configPath = path.join(channelDir, "channel.json");
if (!fs.existsSync(configPath)) {
    console.error(`Missing ${configPath}`);
    process.exit(1);
}

const config = JSON.parse(fs.readFileSync(configPath, "utf8"));
const outDir = path.join(ROOT, "dist", channelId);

const SKIP_DIRS = new Set([
    "node_modules",
    "dist",
    "build",
    "releases",
    ".git",
    ".github",
]);
const SKIP_FILES = new Set(["private-key.pem"]);

function shouldSkip(rel) {
    const parts = rel.split(path.sep);
    if (parts.some((p) => SKIP_DIRS.has(p))) return true;
    if (SKIP_FILES.has(parts[parts.length - 1])) return true;
    return false;
}

function copyRecursive(src, dest) {
    const stat = fs.statSync(src);
    if (stat.isDirectory()) {
        if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
        for (const name of fs.readdirSync(src)) {
            const rel = path.relative(ROOT, path.join(src, name));
            if (shouldSkip(rel)) continue;
            copyRecursive(path.join(src, name), path.join(dest, name));
        }
        return;
    }
    fs.copyFileSync(src, dest);
}

function generateChannelInit(cfg) {
    const opts = cfg.optionLists ?? {};
    const blockUrl = (opts.blockUrl ?? []).map(({ url, state }) => ({
        url,
        state: state !== false,
    }));
    const lockOptions = cfg.lockOptions ?? ["blockUrl", "blockUrlWhite"];
    const lock = {};
    if (typeof opts.blockUrlWhite === "boolean") lock.blockUrlWhite = opts.blockUrlWhite;
    if (blockUrl.length) lock.blockUrl = blockUrl;
    for (const key of lockOptions) {
        if (key === "blockUrl" || key === "blockUrlWhite") continue;
        if (opts[key] !== undefined) lock[key] = opts[key];
    }

    const applyFn = fs.readFileSync(path.join(ROOT, "js", "channel-init.js"), "utf8");
    const applyBlock = applyFn.includes("function applyChannelBuildDefaults")
        ? applyFn.slice(applyFn.indexOf("function applyChannelBuildDefaults"))
        : "";

    const lines = [
        "/**",
        ` * Channel: ${cfg.id} — generated by scripts/build-channel.mjs`,
        " * License: GPL-3.0. Do not edit in dist/; change channels/" + cfg.id + "/channel.json and rebuild.",
        " */",
        "(function () {",
        "    if (typeof G === 'undefined' || !G.OptionLists) { return; }",
        `    G.channelId = ${JSON.stringify(cfg.id)};`,
        `    G.channelDisplayName = ${JSON.stringify(cfg.displayName ?? channelExtensionName(cfg))};`,
        `    G._channelBuildLock = ${JSON.stringify(lock, null, 4).replaceAll("\n", "\n    ")};`,
        `    G._channelLockOptions = ${JSON.stringify(lockOptions)};`,
    ];
    if (cfg.installPage) {
        lines.push(`    G.channelInstallPage = ${JSON.stringify(cfg.installPage)};`);
    }
    if (cfg.license?.apiBase) {
        lines.push(`    G.channelLicenseApi = ${JSON.stringify(cfg.license)};`);
    }
    if (typeof opts.blockUrlWhite === "boolean") {
        lines.push(`    G.OptionLists.blockUrlWhite = ${opts.blockUrlWhite};`);
    }
    if (blockUrl.length) {
        lines.push(`    G.OptionLists.blockUrl = ${JSON.stringify(blockUrl, null, 4).replaceAll("\n", "\n    ")};`);
    }
    for (const [key, val] of Object.entries(opts)) {
        if (key === "blockUrl") continue;
        const t = typeof val;
        if (t === "boolean" || t === "number" || t === "string") {
            lines.push(`    G.OptionLists.${key} = ${JSON.stringify(val)};`);
        }
    }
    lines.push("})();", "", applyBlock);
    return lines.join("\n");
}

function channelExtensionName(cfg) {
    if (cfg.channelNameZh) return `${cfg.channelNameZh}视频下载`;
    return cfg.manifest?.name ?? cfg.displayName ?? cfg.id;
}

function patchManifest(manifest, cfg) {
    const m = { ...manifest, ...(cfg.manifest ?? {}) };
    if (cfg.channelNameZh) {
        m.name = channelExtensionName(cfg);
    }
    if (cfg.repositoryUrl && !cfg.manifest?.homepage_url) {
        m.homepage_url = cfg.repositoryUrl;
    }
    if (cfg.versionSuffix && typeof m.version === "string") {
        m.version = m.version + cfg.versionSuffix;
    }
    if (cfg.license?.apiBase) {
        try {
            const origin = new URL(cfg.license.apiBase).origin + "/*";
            const perms = new Set([...(m.host_permissions || [])]);
            perms.add(origin);
            m.host_permissions = [...perms];
        } catch (e) {
            console.warn("  Invalid license.apiBase:", cfg.license.apiBase);
        }
    }
    return m;
}

function patchLocales(outDir, locales) {
    if (!locales || typeof locales !== "object") return;
    for (const [locale, keys] of Object.entries(locales)) {
        const filePath = path.join(outDir, "_locales", locale, "messages.json");
        if (!fs.existsSync(filePath)) {
            console.warn(`  Skip locale (missing): ${locale}`);
            continue;
        }
        const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
        for (const [key, val] of Object.entries(keys)) {
            const message = typeof val === "string" ? val : val?.message;
            if (message) data[key] = { message };
        }
        fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
        console.log(`  Patched _locales/${locale}/messages.json`);
    }
}

console.log(`Building channel "${channelId}" → ${outDir}`);
if (fs.existsSync(outDir)) {
    fs.rmSync(outDir, { recursive: true, force: true });
}
fs.mkdirSync(outDir, { recursive: true });

for (const name of fs.readdirSync(ROOT)) {
    const src = path.join(ROOT, name);
    if (shouldSkip(path.relative(ROOT, src))) continue;
    if (name === "channels" || name === "scripts" || name === "docs") continue;
    copyRecursive(src, path.join(outDir, name));
}

fs.writeFileSync(path.join(outDir, "js", "channel-init.js"), generateChannelInit(config), "utf8");

const channelIconDir = path.join(channelDir, "icons");
if (fs.existsSync(channelIconDir)) {
    const outImg = path.join(outDir, "img");
    for (const file of fs.readdirSync(channelIconDir)) {
        if (!file.endsWith(".png") || file === "icon-source.png") continue;
        fs.copyFileSync(path.join(channelIconDir, file), path.join(outImg, file));
        console.log(`  Channel icon: img/${file}`);
    }
}

function writeManifest(outDir, filename, cfg) {
    const manifestPath = path.join(outDir, filename);
    if (!fs.existsSync(manifestPath)) return null;
    const manifest = patchManifest(JSON.parse(fs.readFileSync(manifestPath, "utf8")), cfg);
    fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2) + "\n", "utf8");
    return manifest;
}

const manifest = writeManifest(outDir, "manifest.json", config);
writeManifest(outDir, "manifest.firefox.json", config);
if (!manifest) {
    console.error("manifest.json missing in output");
    process.exit(1);
}

patchLocales(outDir, config.locales);

const buildInfo = {
    channelId: config.id,
    displayName: config.displayName ?? channelExtensionName(config),
    extensionName: channelExtensionName(config),
    builtAt: new Date().toISOString(),
    upstreamVersion: manifest.version?.replace(config.versionSuffix ?? "", "") ?? null,
    configSource: `channels/${channelId}/channel.json`,
    repositoryUrl: config.repositoryUrl ?? config.manifest?.homepage_url ?? null,
    installPage: config.installPage ?? null,
    lockOptions: config.lockOptions ?? null,
    license: config.license ?? null,
    pilot: config.pilot ?? null,
};
fs.writeFileSync(path.join(outDir, "channel-build.json"), JSON.stringify(buildInfo, null, 2) + "\n", "utf8");

console.log("Done.");
console.log(`  Load unpacked: ${outDir}`);
console.log(`  Name: ${manifest.name}`);
console.log(`  Version: ${manifest.version}`);
